services:
  trsys.web:
    build:
      context: .
      dockerfile: Dockerfile
    image: trsys-web
    container_name: trsys-web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "7197:80"
      - "7198:443"
    volumes:
      - ./:/app
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      - ~/.aspnet/https:/root/.aspnet/https:ro
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: postgres:latest
    container_name: trsys-db
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-123}
      POSTGRES_DB: ${DB_NAME:-trsys_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
